"""postgis_and_admin_endpoints

Revision ID: 9eaa982bca11
Revises: 9119d573b595
Create Date: 2026-04-27 10:17:51.600277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9eaa982bca11'
down_revision: Union[str, Sequence[str], None] = '9119d573b595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.add_column('activity', sa.Column('route_polyline', sa.Text(), nullable=True))
    op.add_column('activity', sa.Column('map_boundaries', sa.String(), nullable=True))
    op.add_column('activity', sa.Column('visibility_state', sa.String(), nullable=True))
    
    # We must handle the index creation carefully. If location already existed, maybe just create it?
    # Actually PostGIS doesn't always need alembic to create indices this way, but let's keep it.
    # op.create_index('idx_activity_location', 'activity', ['location'], unique=False, postgresql_using='gist')
    
    op.drop_column('activity', 'longitude')
    op.drop_column('activity', 'latitude')
    op.add_column('user', sa.Column('completed_activities_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'completed_activities_count')
    op.add_column('activity', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('activity', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index('idx_activity_location', table_name='activity', postgresql_using='gist')
    op.drop_column('activity', 'visibility_state')
    op.drop_column('activity', 'map_boundaries')
    op.drop_column('activity', 'route_polyline')
    op.drop_column('activity', 'location')
    # ### end Alembic commands ###
